// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KqHOltFYAHgTzskVKj9Nwm9hIbtt9UY',
    appId: '1:257427912545:web:07d5e93bfff22cb2677720',
    messagingSenderId: '257427912545',
    projectId: 'cashify-clone-e924d',
    authDomain: 'cashify-clone-e924d.firebaseapp.com',
    storageBucket: 'cashify-clone-e924d.firebasestorage.app',
    measurementId: 'G-4E77REXBFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhDy6cExtBzbPwJXnETiM4ZKQcHo7PSFU',
    appId: '1:257427912545:android:d0235595817a4f70677720',
    messagingSenderId: '257427912545',
    projectId: 'cashify-clone-e924d',
    storageBucket: 'cashify-clone-e924d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWAve1Om1mKLHUaumc5PPeCR0r2M6VnY',
    appId: '1:257427912545:ios:8f7fbba235c24f22677720',
    messagingSenderId: '257427912545',
    projectId: 'cashify-clone-e924d',
    storageBucket: 'cashify-clone-e924d.firebasestorage.app',
    iosClientId: '257427912545-550g9imijsa4trbqh9fleqrmm4u0chnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chinmayFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWWAve1Om1mKLHUaumc5PPeCR0r2M6VnY',
    appId: '1:257427912545:ios:8f7fbba235c24f22677720',
    messagingSenderId: '257427912545',
    projectId: 'cashify-clone-e924d',
    storageBucket: 'cashify-clone-e924d.firebasestorage.app',
    iosClientId: '257427912545-550g9imijsa4trbqh9fleqrmm4u0chnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chinmayFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5KqHOltFYAHgTzskVKj9Nwm9hIbtt9UY',
    appId: '1:257427912545:web:abac7ea646b3d583677720',
    messagingSenderId: '257427912545',
    projectId: 'cashify-clone-e924d',
    authDomain: 'cashify-clone-e924d.firebaseapp.com',
    storageBucket: 'cashify-clone-e924d.firebasestorage.app',
    measurementId: 'G-35QES6NVC9',
  );
}
